const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {Auth}=require('../src/cobblemine-auth.cjs'),{offlineSession}=require('../src/offline.cjs');
const token='A'.repeat(43),name='ApiPlayer';
const account={id:'a',username:name,minecraftUuid:offlineSession(name).profile.id,points:'42',roles:[{role:'player'}],grades:[]};
const storage={isEncryptionAvailable:()=>true,getSelectedStorageBackend:()=> 'gnome_libsecret',encryptString:s=>Buffer.from('encrypted:'+Buffer.from(s).toString('base64')),decryptString:b=>Buffer.from(b.toString().slice(10),'base64').toString()};
async function fixture(t,fetcher){const folder=await fs.mkdtemp(path.join(require('node:os').tmpdir(),'cobblemine-auth-'));t.after(()=>fs.rm(folder,{recursive:true,force:true}));return new Auth(path.join(folder,'account.encrypted'),storage,()=>{},fetcher);}
const ok=()=>Response.json({accessToken:token,expiresAt:new Date(Date.now()+60000).toISOString(),account});
test('login encrypts only the session and exposes no token or password',async t=>{const a=await fixture(t,async(url,opt)=>{assert.equal(url,'https://api.cobblemine.com/v1/auth/login');assert.equal(opt.redirect,'error');return ok();});const view=await a.login({login:'APIPLAYER',password:'test-password'});assert.equal(view.name,name);assert.equal(view.points,'42');assert.ok(!JSON.stringify(view).includes(token));const file=await fs.readFile(a.file,'utf8');assert.ok(!file.includes(token));assert.ok(!file.includes('test-password'));});
test('restored sessions are checked against API before showing the account',async t=>{const a=await fixture(t,async()=>ok());await a.login({login:name,password:'x'});const b=new Auth(a.file,storage,()=>{},async()=>Response.json(account));assert.equal(b.public(),null);await b.load();assert.equal(b.public().name,name);});
test('network outage cannot launch from a cached identity but permits retry',async t=>{const a=await fixture(t,async()=>ok());await a.login({login:name,password:'x'});a.fetch=async()=>{throw Error('network');};await assert.rejects(()=>a.forLaunch());assert.equal(a.public(),null);assert.ok(a.session);a.fetch=async()=>Response.json(account);assert.equal((await a.forLaunch()).profile.name,name);});
test('revoked session is erased and launch is refused',async t=>{const a=await fixture(t,async()=>ok());await a.login({login:name,password:'x'});a.fetch=async()=>Response.json({}, {status:401});await assert.rejects(()=>a.forLaunch());assert.equal(a.session,null);await assert.rejects(()=>fs.access(a.file));});
test('Minecraft receives the registered name and offline UUID, never the API token',async t=>{const a=await fixture(t,async()=>ok());await a.login({login:'other-input',password:'x'});a.fetch=async()=>Response.json(account);const game=await a.forLaunch();assert.deepEqual(game,offlineSession(name));assert.ok(!JSON.stringify(game).includes(token));});
test('logout revokes the server session and removes the encrypted file',async t=>{const a=await fixture(t,async()=>ok());await a.login({login:name,password:'x'});a.fetch=async(url,opts)=>{assert.ok(url.endsWith('/v1/auth/logout'));assert.equal(opts.headers.Authorization,'Bearer '+token);return new Response(null,{status:204});};await a.logout();assert.equal(a.public(),null);await assert.rejects(()=>fs.access(a.file));});
test('failed logout preserves the current session for another attempt',async t=>{const a=await fixture(t,async()=>ok());await a.login({login:name,password:'x'});a.fetch=async()=>{throw Error('offline');};await assert.rejects(()=>a.logout());assert.equal(a.public().name,name);});
test('without secure storage the token remains in memory',async t=>{const a=await fixture(t,async()=>ok());a.safeStorage={isEncryptionAvailable:()=>false};await a.login({login:name,password:'x'});await assert.rejects(()=>fs.access(a.file));assert.equal(a.public().persistent,false);});
test('incorrect passwords and mismatched Minecraft identities are rejected',async t=>{const a=await fixture(t,async()=>Response.json({}, {status:401}));await assert.rejects(()=>a.login({login:name,password:'wrong'}));assert.equal(a.public(),null);a.fetch=async()=>Response.json({accessToken:token,expiresAt:new Date(Date.now()+60000).toISOString(),account:{...account,minecraftUuid:'bad'}});await assert.rejects(()=>a.login({login:name,password:'x'}));assert.equal(a.public(),null);});
