'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {safePath,httpsUrl,download,atomicJson,readJson}=require('../src/utils.cjs');
const {validateIndex,inspectPack,installPack}=require('../src/packs.cjs');const {defaults,validateSettings,maxRam}=require('../src/settings.cjs');const AdmZip=require('adm-zip');
const workspace=path.resolve(__dirname,'../../../work/test-data');
async function temp(){await fs.mkdir(workspace,{recursive:true});return fs.mkdtemp(path.join(workspace,'case-'));}
const index=()=>({formatVersion:1,game:'minecraft',name:'Test',dependencies:{minecraft:'1.21.1','fabric-loader':'0.19.5'},files:[{path:'mods/test.jar',fileSize:3,hashes:{sha512:crypto.createHash('sha512').update('abc').digest('hex')},downloads:['https://cdn.modrinth.com/data/test.jar']}]});
test('Chemins de modpack : traversée, chemins Windows et collisions refusés',()=>{for(const p of ['../outside','mods/../../x','/tmp/x','C:/x','mods\\evil','mods/CON.jar','mods/a:stream','mods/a.','mods//a'])assert.throws(()=>safePath(workspace,p));assert.equal(safePath(workspace,'mods/good.jar'),path.join(workspace,'mods/good.jar'));const v=index();v.files.push({...v.files[0],path:'MODS/TEST.JAR'});assert.throws(()=>validateIndex(v));});
test('Seuls les packs 1.21.1 Fabric ou NeoForge sont acceptés',()=>{assert.equal(validateIndex(index()).loader,'fabric');const v=index();v.dependencies={'minecraft':'1.21.1',neoforge:'21.1.200'};assert.equal(validateIndex(v).loader,'neoforge');v.dependencies.minecraft='1.20.1';assert.throws(()=>validateIndex(v));});
test('Les mods réservés au serveur sont ignorés',()=>{const v=index();v.files[0].env={client:'unsupported'};assert.equal(validateIndex(v).files.length,0);});
test('Téléchargements : HTTPS obligatoire, aucun identifiant dans les URL',()=>{for(const url of ['http://cdn.modrinth.com/x','file:///a','https://x:y@example.com/a','https://127.0.0.1/a'])assert.throws(()=>httpsUrl(url));assert.equal(httpsUrl('https://cdn.modrinth.com/x'),'https://cdn.modrinth.com/x');});
test('Intégrité : un téléchargement corrompu ne remplace jamais le bon fichier',async()=>{const root=await temp(),file=path.join(root,'mod.jar');await fs.writeFile(file,'old');const orig=global.fetch;global.fetch=async()=>new Response('corrupt',{status:200});try{await assert.rejects(download('https://cdn.modrinth.com/file',file,{hash:'a'.repeat(128)}),/Intégrité/);assert.equal(await fs.readFile(file,'utf8'),'old');assert.deepEqual(await fs.readdir(root),['mod.jar']);}finally{global.fetch=orig;}});
test('Téléchargement vérifié et reprise sans retélécharger',async()=>{const root=await temp(),file=path.join(root,'ok.jar');const orig=global.fetch;let requests=0;global.fetch=async()=>{requests++;return new Response('abc');};try{const options={hash:crypto.createHash('sha512').update('abc').digest('hex'),size:3};await download('https://cdn.modrinth.com/file',file,options);await download('https://cdn.modrinth.com/file',file,options);assert.equal(requests,1);assert.equal(await fs.readFile(file,'utf8'),'abc');}finally{global.fetch=orig;}});
test('Annulation : aucun fichier partiel validé',async()=>{const root=await temp();await assert.rejects(download('https://cdn.modrinth.com/x',path.join(root,'cancel.jar'),{signal:AbortSignal.abort()}));assert.deepEqual(await fs.readdir(root),[]);});
test('Import .mrpack et overrides préservent les configurations existantes',async()=>{const root=await temp(),file=path.join(root,'test.mrpack');const v=index();v.files=[];const zip=new AdmZip();zip.addFile('modrinth.index.json',Buffer.from(JSON.stringify(v)));zip.addFile('overrides/config/test.json',Buffer.from('default'));zip.writeZip(file);const pack=await inspectPack(file);const instance=path.join(root,'instance');await installPack(pack.plan,instance,{archive:file,signal:new AbortController().signal,progress:()=>{}});assert.equal(await fs.readFile(path.join(instance,'config/test.json'),'utf8'),'default');await fs.writeFile(path.join(instance,'config/test.json'),'custom');await installPack(pack.plan,instance,{archive:file,signal:new AbortController().signal,progress:()=>{}});assert.equal(await fs.readFile(path.join(instance,'config/test.json'),'utf8'),'custom');});
test('Réglages : RAM, adresse, ID Microsoft et sauvegarde JSON',async()=>{const cfg={serverAddress:'play.cobblemine.com'};const d=defaults(cfg);assert.equal(validateSettings(d,cfg).serverAddress,cfg.serverAddress);assert.throws(()=>validateSettings({...d,ram:maxRam()+1},cfg));assert.throws(()=>validateSettings({...d,serverAddress:'host:99999'},cfg));assert.throws(()=>validateSettings({...d,microsoftClientId:'secret'},cfg));const file=path.join(await temp(),'settings.json');await atomicJson(file,d);assert.deepEqual(await readJson(file),d);});
test('Les fichiers du pack embarqué sont figés et vérifiables',()=>{const pack=require('../builtin-pack.json');assert.equal(pack.minecraft,'1.21.1');assert.ok(pack.files.length>=2);for(const file of pack.files){safePath(workspace,file.path);assert.match(file.sha512,/^[a-f0-9]{128}$/);assert.ok(file.size>0);}});

