'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),AdmZip=require('adm-zip');
const {safePath,noSymlinks,httpsUrl,download,hashFile,atomicJson}=require('./utils.cjs');
function validateIndex(index){if(index?.formatVersion!==1||index.game!=='minecraft'||index.dependencies?.minecraft!=='1.21.1'||!Array.isArray(index.files)||index.files.length>10000)throw Error('Ce modpack doit être au format Modrinth pour Minecraft 1.21.1.');
 const deps=index.dependencies;const loaders=['fabric-loader','neoforge'].filter(x=>deps[x]);if(loaders.length!==1)throw Error('Le modpack doit utiliser Fabric ou NeoForge.');if(Object.keys(deps).some(k=>!['minecraft',...loaders].includes(k)))throw Error('Chargeur supplémentaire non pris en charge.');
 const loaderVersion=deps[loaders[0]];if(typeof loaderVersion!=='string'||!/^[0-9][0-9a-zA-Z.+_-]{0,60}$/.test(loaderVersion))throw Error('Version du chargeur invalide.');
 const seen=new Set();for(const f of index.files){safePath('/instance',f.path);const key=f.path.toLowerCase();if(seen.has(key))throw Error('Chemin dupliqué dans le modpack.');seen.add(key);if(!f.hashes||!/^([0-9a-f]{128})$/i.test(f.hashes.sha512)||!Array.isArray(f.downloads)||!f.downloads.length||!Number.isSafeInteger(f.fileSize)||f.fileSize<0||f.fileSize>1024**3)throw Error('Fichier de modpack invalide.');f.downloads.forEach(u=>httpsUrl(u));if(f.env?.client&&!['required','optional','unsupported'].includes(f.env.client))throw Error('Environnement client invalide.');}
 if(index.files.reduce((sum,f)=>sum+f.fileSize,0)>10*1024**3)throw Error('Modpack trop volumineux.');
 return {name:String(index.name||'Modpack importé').slice(0,100),minecraft:'1.21.1',loader:loaders[0]==='neoforge'?'neoforge':'fabric',loaderVersion,files:index.files.filter(f=>f.env?.client!=='unsupported').map(f=>({path:f.path,urls:f.downloads,size:f.fileSize,sha512:f.hashes.sha512.toLowerCase()}))};}
async function inspectPack(file){const stat=await fs.stat(file);if(stat.size>1024**3)throw Error('Archive trop volumineuse.');const zip=new AdmZip(file);const entries=zip.getEntries();if(entries.length>20000)throw Error('Trop de fichiers dans le modpack.');
 let total=0;for(const e of entries){const name=e.entryName.replace(/\/$/,'');safePath('/archive',name);if(((e.attr>>>16)&0xf000)===0xa000)throw Error('Les liens symboliques ne sont pas autorisés.');total+=e.header.size;if(e.header.size>512*1024**2||total>2*1024**3)throw Error('Archive décompressée trop volumineuse.');}
 const entry=zip.getEntry('modrinth.index.json');if(!entry||entry.header.size>5*1024**2)throw Error('Fichier modrinth.index.json introuvable. Exporte ton pack au format .mrpack.');const plan=validateIndex(JSON.parse(entry.getData().toString('utf8')));return {zip,plan,id:(await hashFile(file)).slice(0,24)};}
async function installPack(plan,instance,{signal,progress,archive}={}){
 const files=plan.files;let completed=0;for(const f of files){signal.throwIfAborted();const dest=safePath(instance,f.path);await noSymlinks(instance,dest);progress('Mods : '+path.basename(f.path),completed,files.length);let error;for(const url of f.urls){try{await download(url,dest,{hash:f.sha512,size:f.size,signal,onProgress:(bytes,total)=>progress('Mods : '+path.basename(f.path),completed+(total?bytes/total:0),files.length)});error=null;break;}catch(e){error=e;if(signal.aborted)throw e;}}if(error)throw error;completed++;}
 if(archive){const zip=new AdmZip(archive),written=new Set();for(const prefix of ['overrides/','client-overrides/']){for(const e of zip.getEntries()){if(e.isDirectory||!e.entryName.startsWith(prefix))continue;signal.throwIfAborted();const relative=e.entryName.slice(prefix.length);const dest=safePath(instance,relative);await noSymlinks(instance,dest);await fs.mkdir(path.dirname(dest),{recursive:true});const existing=await fs.stat(dest).catch(()=>null);if(existing&&!written.has(dest))continue;await fs.writeFile(dest,e.getData(),{flag:written.has(dest)?'w':'wx'});written.add(dest);}}}
 await atomicJson(path.join(instance,'cobblemine-pack.json'),{name:plan.name,files:files.map(f=>({path:f.path,sha512:f.sha512})),installedAt:new Date().toISOString()});}
module.exports={validateIndex,inspectPack,installPack};
