'use strict';
const $=s=>document.querySelector(s),api=window.cobblemine;
let state,toastTimer,authDialog=false,dialogAction=null,deviceCode='',formDirty=false;
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function modal(title,body,label='Compris',action=null){authDialog=false;$('#auth-actions').hidden=true;$('#dialog-title').textContent=title;$('#dialog-body').textContent=body;$('#dialog-kicker').textContent='COBBLEMINE';$('#dialog-ok').textContent=label;dialogAction=action;if(!$('#dialog').open)$('#dialog').showModal();}
function profileForm(){const offline=$('#authMode').value==='offline';$('#offline-profile').hidden=!offline;$('#offline-note').hidden=!offline;$('#offlineName').required=offline;$('#offlineName').disabled=!offline;$('.auth-settings').hidden=offline;$('#profile-save').textContent=offline?'Utiliser ce profil':'Continuer avec Microsoft';}
$('#authMode').addEventListener('change',profileForm);
function settingsForm(s){$('#ram').max=state.maxRam;$('.range-labels span:last-child').textContent=state.maxRam+' Go';$('#ram').value=s.ram;$('#ram-value').textContent=s.ram+' Go';$('#resolution').value=s.resolution;$('#fullscreen').checked=s.fullscreen;$('#motion').checked=s.motion;$('#server').value=s.serverAddress;$('#autoJoin').checked=s.autoJoin;document.body.classList.toggle('no-motion',!s.motion);formDirty=false;}
function render(s){state=s;$('#launcher-version').textContent=s.version;renderUpdate(s.update);const busy=Boolean(s.busy),locked=busy||s.running;$('#login span:nth-child(2)').textContent=s.account?s.account.name:'Choisir un profil';$('#login').disabled=locked;$('.status-dot').classList.toggle('connected',!!s.account);$('#status-title').textContent=s.running?'Minecraft est ouvert':s.busy||s.installed?.name||'Minecraft est prêt à être installé';$('#status-detail').textContent=s.account?(s.account.offline?'Profil local · ':'Connecté · ')+s.account.name:'Connecte-toi pour jouer';$('#pack-label').textContent=s.selection?.name||s.builtin;$('#selected-pack').textContent=s.selection?.name||s.builtin;$('#copy-server').textContent=s.settings.serverAddress||'Serveur à configurer';$('#play').textContent=s.running?'EN JEU':busy?'PRÉPARATION…':s.installed?'▶ JOUER':'↓ INSTALLER';$('#play').disabled=locked;for(const id of ['install','import-pack','base-pack','update-pack','save','reset'])$('#'+id).disabled=locked;$('#settings-form').querySelectorAll('input,select').forEach(el=>el.disabled=locked);$('#download-progress').hidden=!busy;if(s.progress)renderProgress(s.progress);else if(busy){$('#progress-label').textContent=s.busy;$('#progress').removeAttribute('value');}if(!formDirty)settingsForm(s.settings);}
function renderProgress(event){$('#progress-label').textContent=event.label;if(event.total>0){$('#progress').max=event.total;$('#progress').value=Math.min(event.total,event.done);}else $('#progress').removeAttribute('value');}
async function call(name,...args){if(!api){modal('Ouvre l’application Cobblemine','Cette page fait partie de l’application de bureau. Lance Cobblemine depuis son exécutable pour installer Minecraft et connecter ton compte.');return;}
 try{return await api[name](...args);}catch(e){if(authDialog){authDialog=false;$('#dialog').close();}modal('Impossible de terminer',e.message);throw e;}}
function action(id,handler){$('#'+id).addEventListener('click',()=>Promise.resolve().then(handler).catch(()=>{}));}
function route(){const page=['accueil','actualites','parametres'].includes(location.hash.slice(1))?location.hash.slice(1):'accueil';document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==page);document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#main').scrollTop=0;}
window.addEventListener('hashchange',route);route();
$('#ram').addEventListener('input',()=>$('#ram-value').textContent=$('#ram').value+' Go');$('#settings-form').addEventListener('input',()=>formDirty=true);$('#motion').addEventListener('change',()=>document.body.classList.toggle('no-motion',!$('#motion').checked));
$('#settings-form').addEventListener('submit',async event=>{event.preventDefault();try{const value={authMode:state.settings.authMode,offlineName:state.settings.offlineName,ram:Number($('#ram').value),resolution:$('#resolution').value,fullscreen:$('#fullscreen').checked,motion:$('#motion').checked,serverAddress:$('#server').value,autoJoin:$('#autoJoin').checked,microsoftClientId:state.settings.microsoftClientId};const result=await call('save-settings',value);if(result){formDirty=false;render(result);notify('Réglages enregistrés.');}}catch{}});
action('reset',()=>modal('Rétablir les réglages ?','La mémoire et l’affichage retrouveront leurs valeurs par défaut. Ton profil, l’adresse du serveur et l’identifiant Microsoft seront conservés.','Rétablir',async()=>{const result=await call('reset-settings');if(result){formDirty=false;render(result);notify('Réglages rétablis.');}}));
action('login',async()=>{if(!state)return call('state');$('#authMode').value=state.settings.authMode;$('#offlineName').value=state.settings.offlineName;$('#clientId').value=state.settings.microsoftClientId;$('#profile-error').hidden=true;$('#profile-logout').hidden=!state.account||state.account.offline;profileForm();$('#profile-dialog').showModal();if(state.settings.authMode==='offline')$('#offlineName').focus();});
action('play',async()=>{if(!state)return;if(!state.installed){await call('install');notify('Minecraft et Cobblemon sont installés.');return;}if(!state.account){$('#login').click();return;}await call('play');});
action('install',async()=>{await call('install');notify('Installation vérifiée.');});
action('import-pack',async()=>{const result=await call('import-pack');if(result)notify('Modpack importé : '+result.name);});
action('base-pack',()=>modal('Utiliser la base Cobblemon ?','Le launcher utilisera la base fournie. Ton modpack précédent et ses mondes seront conservés dans leur dossier.','Utiliser la base',()=>call('base-pack')));
action('update-pack',async()=>{await call('update-pack');notify('Modpack mis à jour.');});
action('cancel',()=>call('cancel'));action('open-folder',()=>call('open-folder'));action('open-logs',()=>call('open-logs'));action('copy-server',async()=>{await call('copy-server');notify('Adresse du serveur copiée.');});
action('copy-code',async()=>{await call('copy-code',deviceCode);notify('Code copié.');});action('open-microsoft',()=>call('open-microsoft'));action('open-shop',()=>call('open-shop'));
action('read-news',()=>modal('L’inconnu t’attend.','Cobblemine est un projet de serveur Minecraft Cobblemon orienté aventure et exploration.\n\nLe launcher permet de préparer ton installation et de rejoindre le serveur. Le modpack exact du serveur sera ajouté lorsqu’il sera prêt.'));
action('dialog-ok',async()=>{const callback=dialogAction;dialogAction=null;const wasAuth=authDialog;authDialog=false;$('#dialog').close();if(wasAuth)await call('cancel');else await callback?.();});
$('#dialog .dialog-close').addEventListener('click',()=>$('#dialog').close());$('#dialog').addEventListener('close',()=>{if(authDialog){authDialog=false;api?.cancel().catch(()=>{});}dialogAction=null;});
if(api){api.onEvent(event=>{if(event.type==='state')render(event.state);if(event.type==='launcher-update')renderUpdate(event.update);if(event.type==='progress')renderProgress(event);if(event.type==='auth-code'){modal('Connecte ton compte Microsoft','Ouvre la page Microsoft et saisis le code ci-dessous.','Annuler');authDialog=true;deviceCode=event.code;$('#device-code').textContent=deviceCode;$('#auth-actions').hidden=false;}if(event.type==='game-exit'){if(event.code)modal('Minecraft s’est arrêté','Le jeu a quitté avec le code '+event.code+'. Consulte le journal du launcher pour identifier le problème.');else notify('Minecraft est fermé.');}});call('state').then(render).catch(()=>{});}else{modal('Aperçu de l’application','Pour utiliser l’installation et la connexion, lance l’exécutable Cobblemine.');}


function renderUpdate(u){if(!u)return;const downloading=u.status==='downloading',ready=u.status==='ready';const message=u.message+(downloading&&Number.isFinite(u.percent)?' '+u.percent+' %':'');$('#launcher-update-message').textContent=message;$('#launcher-update-status').textContent=message;$('#launcher-update-banner').hidden=true;$('#restart-launcher').hidden=!ready;$('#defer-launcher').hidden=!ready;$('#restart-launcher').disabled=Boolean(state?.busy||state?.running);$('#check-launcher-update').disabled=['disabled','checking','downloading','installing'].includes(u.status);}
action('check-launcher-update',()=>call('check-launcher-update'));
action('restart-launcher',()=>call('install-launcher-update'));
action('defer-launcher',()=>call('defer-launcher-update'));


action('profile-close',()=>$('#profile-dialog').close());action('profile-cancel',()=>$('#profile-dialog').close());
let profileSaving=false;
$('#profile-form').addEventListener('submit',async event=>{event.preventDefault();if(profileSaving||!state)return;profileSaving=true;$('#profile-save').disabled=true;$('#profile-error').hidden=true;try{const result=await api['save-settings']({...state.settings,authMode:$('#authMode').value,offlineName:$('#offlineName').value,microsoftClientId:$('#clientId').value});render(result);if(result.settings.authMode==='microsoft'&&!result.account&&!result.settings.microsoftClientId){$('.auth-settings').open=true;throw Error('La connexion Microsoft doit être configurée pour Cobblemine. Tu peux aussi choisir Sans compte Microsoft.');}$('#profile-dialog').close();if(result.settings.authMode==='microsoft'&&!result.account){await call('login');if(authDialog){authDialog=false;$('#dialog').close();}notify('Compte Microsoft connecté.');}else notify('Profil sélectionné.');}catch(e){$('#profile-error').textContent=e.message;$('#profile-error').hidden=false;}finally{profileSaving=false;$('#profile-save').disabled=false;}});
action('profile-logout',async()=>{await call('logout');$('#profile-dialog').close();notify('Compte déconnecté.');});
