'use strict';
const $=s=>document.querySelector(s),api=window.cobblemine;
let state,toastTimer,authDialog=false,dialogAction=null,deviceCode='',formDirty=false;
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function modal(title,body,label='Compris',action=null){authDialog=false;$('#auth-actions').hidden=true;$('#dialog-title').textContent=title;$('#dialog-body').textContent=body;$('#dialog-kicker').textContent='COBBLEMINE';$('#dialog-ok').textContent=label;dialogAction=action;if(!$('#dialog').open)$('#dialog').showModal();}

function settingsForm(s){$('#ram').max=state.maxRam;$('.range-labels span:last-child').textContent=state.maxRam+' Go';$('#ram').value=s.ram;$('#ram-value').textContent=s.ram+' Go';$('#resolution').value=s.resolution;$('#fullscreen').checked=s.fullscreen;$('#motion').checked=s.motion;$('#server').value=s.serverAddress;$('#autoJoin').checked=s.autoJoin;document.body.classList.toggle('no-motion',!s.motion);formDirty=false;}
let avatarName='';
function renderAvatar(name){if(avatarName===name)return;avatarName=name;const img=$('#account-skin');img.src='assets/app-icon.png';if(name)api['skin-avatar']().then(src=>{if(avatarName===name&&src)img.src=src;}).catch(()=>{});}
function render(s){state=s;renderAvatar(s.account?.name||'');renderSignin(s);$('#launcher-version').textContent=s.version;renderUpdate(s.update);const busy=Boolean(s.busy),locked=busy||s.running;$('#login span:nth-child(2)').textContent=s.account?s.account.name:'Choisir un profil';$('#login').disabled=locked;$('.status-dot').classList.toggle('connected',!!s.account);$('#status-title').textContent=s.running?'Minecraft est ouvert':s.busy||'';$('#status-title').hidden=!s.running&&!s.busy;$('#status-detail').textContent=s.account?'Connecté · '+s.account.name:'Connecte-toi pour jouer';$('#pack-label').textContent=s.selection?.name||s.builtin;$('#selected-pack').textContent=s.selection?.name||s.builtin;$('#copy-server').textContent=s.settings.serverAddress||'Serveur à configurer';$('#play').textContent=s.running?'EN JEU':busy?'PRÉPARATION…':s.installed?'▶ JOUER':'↓ INSTALLER';$('#play').disabled=locked||!s.account;for(const id of ['install','import-pack','base-pack','update-pack','save','reset'])$('#'+id).disabled=locked;$('#settings-form').querySelectorAll('input,select').forEach(el=>el.disabled=locked);$('#download-progress').hidden=!busy;if(s.progress)renderProgress(s.progress);else if(busy){$('#progress-label').textContent=s.busy;$('#progress').removeAttribute('value');}if(!formDirty)settingsForm(s.settings);}
function renderProgress(event){$('#progress-label').textContent=event.label;if(event.total>0){$('#progress').max=event.total;$('#progress').value=Math.min(event.total,event.done);}else $('#progress').removeAttribute('value');}
async function call(name,...args){if(!api){modal('Ouvre l’application Cobblemine','Cette page fait partie de l’application de bureau. Lance Cobblemine depuis son exécutable pour installer Minecraft et connecter ton compte.');return;}
 try{return await api[name](...args);}catch(e){if(authDialog){authDialog=false;$('#dialog').close();}modal('Impossible de terminer',e.message);throw e;}}
function action(id,handler){$('#'+id).addEventListener('click',()=>Promise.resolve().then(handler).catch(()=>{}));}
function route(){const page=['accueil','actualites','parametres'].includes(location.hash.slice(1))?location.hash.slice(1):'accueil';document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==page);document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#main').scrollTop=0;}
window.addEventListener('hashchange',route);route();
$('#ram').addEventListener('input',()=>$('#ram-value').textContent=$('#ram').value+' Go');$('#settings-form').addEventListener('input',()=>formDirty=true);$('#motion').addEventListener('change',()=>document.body.classList.toggle('no-motion',!$('#motion').checked));
$('#settings-form').addEventListener('submit',async event=>{event.preventDefault();try{const value={authMode:state.settings.authMode,offlineName:state.settings.offlineName,ram:Number($('#ram').value),resolution:$('#resolution').value,fullscreen:$('#fullscreen').checked,motion:$('#motion').checked,serverAddress:$('#server').value,autoJoin:$('#autoJoin').checked,microsoftClientId:state.settings.microsoftClientId};const result=await call('save-settings',value);if(result){formDirty=false;render(result);notify('Réglages enregistrés.');}}catch{}});
action('reset',()=>modal('Rétablir les réglages ?','La mémoire et l’affichage retrouveront leurs valeurs par défaut. Ton compte et l’adresse du serveur seront conservés.','Rétablir',async()=>{const result=await call('reset-settings');if(result){formDirty=false;render(result);notify('Réglages rétablis.');}}));
action('login',()=>{if(!state?.account)return;$('#profile-name').textContent=state.account.name;$('#profile-points').textContent=state.account.points+' points';$('#profile-grades').textContent=state.account.grades.map(g=>g.grade).join(', ')||'Aucun grade actif';$('#profile-session-note').textContent=state.account.persistent?'Session mémorisée sur cet ordinateur.':'Session conservée uniquement pendant cette ouverture.';$('#profile-dialog').showModal();});
action('play',async()=>{if(!state)return;if(!state.installed){await call('install');notify('Minecraft et Cobblemon sont installés.');return;}if(!state.account){$('#login').click();return;}await call('play');});
action('install',async()=>{await call('install');notify('Installation vérifiée.');});
action('import-pack',async()=>{const result=await call('import-pack');if(result)notify('Modpack importé : '+result.name);});
action('base-pack',()=>modal('Utiliser la base Cobblemon ?','Le launcher utilisera la base fournie. Ton modpack précédent et ses mondes seront conservés dans leur dossier.','Utiliser la base',()=>call('base-pack')));
action('update-pack',async()=>{await call('update-pack');notify('Modpack mis à jour.');});
action('cancel',()=>call('cancel'));action('open-folder',()=>call('open-folder'));action('open-logs',()=>call('open-logs'));action('copy-server',async()=>{await call('copy-server');notify('Adresse du serveur copiée.');});
action('copy-code',async()=>{await call('copy-code',deviceCode);notify('Code copié.');});action('open-microsoft',()=>call('open-microsoft'));action('open-shop',()=>call('open-shop'));
action('read-news',()=>modal('L’inconnu t’attend.','Cobblemine est un projet de serveur Minecraft Cobblemon orienté aventure et exploration.\n\nLe launcher permet de préparer ton installation et de rejoindre le serveur. Le modpack exact du serveur sera ajouté lorsqu’il sera prêt.'));
action('dialog-ok',async()=>{const callback=dialogAction;dialogAction=null;const wasAuth=authDialog;authDialog=false;$('#dialog').close();if(wasAuth)await call('cancel');else await callback?.();});
$('#dialog .dialog-close').addEventListener('click',()=>$('#dialog').close());$('#dialog').addEventListener('close',()=>{if(authDialog){authDialog=false;api?.cancel().catch(()=>{});}dialogAction=null;});
if(api){api.onEvent(event=>{if(event.type==='state')render(event.state);if(event.type==='launcher-update')renderUpdate(event.update);if(event.type==='progress')renderProgress(event);if(event.type==='auth-code'){modal('Connecte ton compte Microsoft','Ouvre la page Microsoft et saisis le code ci-dessous.','Annuler');authDialog=true;deviceCode=event.code;$('#device-code').textContent=deviceCode;$('#auth-actions').hidden=false;}if(event.type==='game-exit'){if(event.code)modal('Minecraft s’est arrêté','Le jeu a quitté avec le code '+event.code+'. Consulte le journal du launcher pour identifier le problème.');else notify('Minecraft est fermé.');}});call('state').then(render).catch(()=>{});}else{modal('Aperçu de l’application','Pour utiliser l’installation et la connexion, lance l’exécutable Cobblemine.');}


function renderUpdate(u){if(!u)return;const downloading=u.status==='downloading',ready=u.status==='ready';const message=u.message+(downloading&&Number.isFinite(u.percent)?' '+u.percent+' %':'');$('#launcher-update-message').textContent=message;$('#launcher-update-status').textContent=message;$('#launcher-update-banner').hidden=true;$('#restart-launcher').hidden=!ready;$('#defer-launcher').hidden=!ready;$('#restart-launcher').disabled=Boolean(state?.busy||state?.running);$('#check-launcher-update').disabled=['disabled','checking','downloading','installing'].includes(u.status);}
action('check-launcher-update',()=>call('check-launcher-update'));
action('restart-launcher',()=>call('install-launcher-update'));
action('defer-launcher',()=>call('defer-launcher-update'));



function renderSignin(s){const connected=Boolean(s.account);$('#signin').hidden=connected;$('.launcher').hidden=!connected;$('#signin-fields').disabled=Boolean(s.busy);$('#signin-submit').firstChild.textContent=s.busy?'Connexion… ':'Se connecter ';$('#restore-session').hidden=connected||!s.hasSavedSession;$('#restore-session').disabled=Boolean(s.busy);$('#signin-note').textContent=s.authNotice||'';if(!connected&&$('#profile-dialog').open)$('#profile-dialog').close();}
$('#signin-form').addEventListener('submit',async event=>{event.preventDefault();if(state?.busy)return;$('#signin-error').hidden=true;$('#signin-fields').disabled=true;try{const result=await api.login({login:$('#signin-login').value,password:$('#signin-password').value});$('#signin-password').value='';render(result);location.hash='accueil';}catch(e){$('#signin-password').value='';$('#signin-error').textContent=e.message;$('#signin-error').hidden=false;}finally{$('#signin-fields').disabled=false;}});
action('show-password',()=>{const show=$('#signin-password').type==='password';$('#signin-password').type=show?'text':'password';$('#show-password').textContent=show?'Masquer':'Afficher';$('#show-password').setAttribute('aria-label',show?'Masquer le mot de passe':'Afficher le mot de passe');$('#show-password').setAttribute('aria-pressed',String(show));});
action('open-register',()=>call('open-register'));action('open-account',()=>call('open-account'));
action('restore-session',async()=>{try{render(await api['restore-session']());$('#signin-error').hidden=true;}catch(e){$('#signin-error').textContent=e.message;$('#signin-error').hidden=false;}});
action('profile-close',()=>$('#profile-dialog').close());
action('profile-logout',async()=>{await call('logout');$('#profile-dialog').close();$('#signin-password').value='';$('#signin-password').type='password';$('#show-password').textContent='Afficher';$('#show-password').setAttribute('aria-pressed','false');location.hash='accueil';$('#signin-login').focus();});

function renderWindow(s){const maximized=Boolean(s.maximized);$('#window-maximize').setAttribute('aria-label',maximized?'Restaurer':'Agrandir');$('#window-maximize').title=maximized?'Restaurer':'Agrandir';$('#maximize-shape').setAttribute('d',maximized?'M5.5 3.5h7v7M3.5 5.5h7v7h-7Z':'M3.5 3.5h9v9h-9Z');}
for(const name of ['window-minimize','window-maximize','window-close'])action(name,()=>call(name));
if(api){api.onEvent(event=>{if(event.type==='window-state')renderWindow(event);});api['window-state']().then(renderWindow).catch(()=>{});}
